spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api
  port: 8099
